const ReminiscenceSession = require('../models/ReminiscenceSession');
const { success } = require('../utils/responseFormat');

// POST /reminiscence-sessions — Save Reminiscence Session
// Note: the "questions" array is generated by AI-2's logic on the frontend/AI side —
// this endpoint just stores whatever array it's given.
async function saveReminiscenceSession(req, res) {
  const { patientId, memoryId, questions } = req.body;
  const session = await ReminiscenceSession.create({ patientId, memoryId, questions });
  return success(res, {
    id: session._id.toString(),
    patientId: session.patientId.toString(),
    memoryId: session.memoryId.toString(),
    questions: session.questions,
    createdAt: session.createdAt,
  }, 201);
}

// GET /patients/:id/reminiscence-sessions — Get Reminiscence History
async function getReminiscenceHistory(req, res) {
  const sessions = await ReminiscenceSession.find({ patientId: req.params.id }).sort({ createdAt: -1 });
  return success(res, sessions.map(s => ({
    id: s._id.toString(),
    memoryId: s.memoryId.toString(),
    questions: s.questions,
    createdAt: s.createdAt,
  })));
}

module.exports = { saveReminiscenceSession, getReminiscenceHistory };
